version: '3.7'

services:
  mysql-bookstore:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 's3cr3t'
      MYSQL_DATABASE: 'bookstore'
      MYSQL_USER: 'bookstore'
      MYSQL_PASSWORD: 'bookstore'
    ports:
      - "3306:3306"
    volumes:
      - mysql-bookstore:/var/lib/mysql
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp --disable-log-bin

networks:
  default:
    name: bookstore
volumes:
  mysql-bookstore:
    name: mysql-bookstore
    external: true
