version: '3.7'

services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9988:9988"

  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  proxy:
    image: nginx:1.17
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
#    depends_on:
#      - backend
#      - frontend
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 's3cr3t'
      MYSQL_DATABASE: 'bookstore'
      MYSQL_USER: 'bookstore'
      MYSQL_PASSWORD: 'bookstore'
    ports:
      - "3306:3306"
    volumes:
      - mysql-bookstore:/var/lib/mysql
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp --disable-log-bin

networks:
  default:
    name: bookstore

volumes:
  mysql-bookstore:
    name: mysql-bookstore
    external: true
